const BREAKPOINT = "768px";
const BREAKPOINT_TABLET = "1024px";

export const GRID = {
  COLUMNS: 12,
  MAX_WIDTH: 1800,
  PADDING: 20,
  GAP: 20,
  ROW_GAP: "0.3rem",

  COLUMNS_TABLET: 8,
  PADDING_TABLET: 30,
  GAP_TABLET: "1rem",
  ROW_GAP_TABLET: "0.625rem",

  COLUMNS_MOBILE: 4,
  PADDING_MOBILE: 20,
  GAP_MOBILE: "1rem",
  ROW_GAP_MOBILE: "1rem",

  BREAKPOINT,
  BREAKPOINT_TABLET,

  MEDIA_MOBILE: `(max-width: ${BREAKPOINT})`,
  MEDIA_TABLET: `(max-width: ${BREAKPOINT_TABLET})`,
};

export default GRID;
